### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by thetre97** [RomainLanz/adonis-graphql#12]
Could anyone provide an example of using the adonis authentication with this?
For example, I have a login resolver, where I want to create a JWT Token and return it to the user.

```javascript
 login: async (parent, args, { auth }, info) => {
      try {
        const token = await auth.attempt(args.auth)
        return { token }
      } catch (error) {
        throw new GraphQLError(error.message)
      }
    }
```

I can see auth is passed in the context if I log it, but it just returns "Cannot convert object to primitive value" when I try to use it like the above. Would be glad of any help.

Thanks

**Comment by andruu** [comment]
const { token } = await ...

**Comment by Alex237** [comment]
Hello @thetre97 .

This article might help you 
[https://medium.com/react-native-training/building-chatty-part-7-authentication-in-graphql-cd37770e5ab3](https://medium.com/react-native-training/building-chatty-part-7-authentication-in-graphql-cd37770e5ab3)

i adapted the content of the article with the doc [https://adonisjs.com/docs/4.1/authentication#_jwt](https://adonisjs.com/docs/4.1/authentication#_jwt) to make  adonis authentication

**Comment by thetre97** [comment]
Thanks @Alex237 , I will check that out.
Sorry to open two issues...
