### ISSUE TITLE
Request more documentations

### ISSUE THREAD

**Issue by annymosse** [RomainLanz/adonis-graphql#13]
How to access the parent fields ?
GraphQl of adonnisJS look like deferent to the others GraphQL of (`expressjs,koa,hapi...`);
hopfully you can make a documentation in the main website , as i believe of the GraphQL and the similaires as `falcor` are the future of the web instead of the traditional RESTful API;
sorry about my weakness in English

**Comment by RomainLanz** [comment]
Hey @annymosse! 👋 

Sorry for the late reply, I was completely busy with my work.
I'll provide more documentation and probably refactor some part of this package.

This package was more an attempt to make GraphQL work with Adonis via some current package (that I personally don't like, the `resolver` syntax is just ugly), but it gonna takes more time to implement a better version.

**Comment by annymosse** [comment]
thanks @RomainLanz  becouse i had a problem to get the parent and when i searched more i got your syntax look like newer in comparaision to the graphQl docs, i liked your syntax method but for now it's not effective as apollo ,whenever it's more easy in other side.

**Comment by RomainLanz** [comment]
Actually, it's the same syntax than others GraphQL engine.
Which difference do you see?
