### ISSUE TITLE
Fatal error when graphql.options is undefined

### ISSUE THREAD

**Issue by yariksav** [RomainLanz/adonis-graphql#18]
I didn't have an defined graphql.config param and after update my aplication falled down

with error "Uncaught TypeError: Cannot convert undefined or null to object" in 

https://github.com/RomainLanz/adonis-graphql/blob/678bd93885b2ee241807210adbeae7d156bb3e36/src/Server/index.js#L34

I suppose 
```js
this.$options = config.get("graphql.options");
```

should have an default value, like 
```js
this.$options = config.get("graphql.options") || {}
```

**Comment by RomainLanz** [comment]
Yup,

Happy to accept a PR!
