### ISSUE TITLE
Adding middleware

### ISSUE THREAD

**Issue by travis-r6s** [RomainLanz/adonis-graphql#20]
Is there any way to add middleware? For instance: https://github.com/maticzav/graphql-shield

I tried 

```javascript
const permissions = require('./permissions')

module.exports = {
  options: {
    debug: true,
    endpointURL: '/',
    tracing: true,
    cacheControl: true
    middlewares: [permissions], // Here
  },

  middlewares: [permissions], // And here
  schema: join(__dirname, '../app/Schema'),
  resolvers: join(__dirname, '../app/Resolvers'),
}
```

**Comment by ghmendonca** [comment]
@thetre97 how did you solve this? I'm having trouble with this same thing, I want to use graphql shield and pass the permissions as a middleware..

**Comment by travis-r6s** [comment]
@ghmendonca Afraid I didn't - I stopped using Adonis, and used Apollo Server directly as I only needed a GraphQL server and not all the other Adonis goodness.

It also seems that this repo isn't that actively maintained anymore...

**Comment by ghmendonca** [comment]
I see, I hate adonis but is what they use in the company that I work.. I guess I'll have to spend hours and hours to figure this out :/ but thanks man!
