### ISSUE TITLE
Error: Specified query type "Query" not found in document.

### ISSUE THREAD

**Issue by devalexandre** [RomainLanz/adonis-graphql#27]
``` 
Error: Specified query type "Query" not found in document.

at /Users/alexandre/projects/meusclientes/start/routes.js(anonymous):17
12  | http://adonisjs.com/docs/4.1/routing
13  |
14  */
15  /** @type {typeof import('@adonisjs/framework/src/Route/Manager')} */
16  const Route = use("Route");
17  const GraphQLServer = use("GraphQLServer");
18  
19  Route.post("/", context => {
20    return GraphQLServer.handle(context);
21  });
22  
```

**Comment by implid** [comment]
Hi, the npm package is not up to date

you can add a / in the `config/graphql.js` file on ..app/Schema
```
module.exports = {
  options: {
    debug: false,
    endpointURL: '/',
  },

  schema: join(__dirname, '../app/Schema'),
  resolvers: join(__dirname, '../app/Resolvers'),
}
```
instead of
```
module.exports = {
  options: {
    debug: false,
    endpointURL: '/',
  },

  schema: join(__dirname, '..app/Schema'),
  resolvers: join(__dirname, '../app/Resolvers'),
}
```

npm repo must be updated #25

**Comment by anaalicefig** [comment]
I have the same error. @implid i did what you said, but still doesn't work

**Comment by implid** [comment]
You need to have a **Schema** folder  in the **app** dir and at least one **.gphql shema** with a **Query type.**

**Comment by anaalicefig** [comment]
@implid yeah, that works. Thank you

**Comment by annymosse** [comment]
@anaalicefig please close the issue report.

**Comment by anaalicefig** [comment]
@annymosse it's not mine

**Comment by annymosse** [comment]
@anaalicefig sorry and thanks , @devalexandre please close this issue report.

**Comment by they-cloned-me** [comment]
@RomainLanz, @anaalicefig, @annymosse
For some reason, I still manage to get that error. I have included a screenshot.

![ss](https://user-images.githubusercontent.com/15837064/71459472-47ef3900-276d-11ea-8e3f-911022d8ec5d.png)

**Comment by annymosse** [comment]
@fsavalam did you made the reslovers(users,user)
```js
// app/Resolvers/Hello.js
module.exports = {
  Query: {
    users: () => 'hello all users'
    user: (root,args,context, info) => `hello UserById ${args.id}`
  }
}
```

**Comment by they-cloned-me** [comment]
![dd](https://user-images.githubusercontent.com/15837064/71520956-54b28080-2884-11ea-9d07-d7be86404253.png)

Yes @annymosse

**Comment by they-cloned-me** [comment]
I seriously don't know why this is happening. I have installed a clean copy of adonis, and followed all the steps above, and as in the documentation. But the server won't just start

**Comment by annymosse** [comment]
i noticed adonis command won't start sometimes even without the `dev` argument 
```bash
$ adonis serve --dev
$ adonis serve
``` 
doesn't work without error output

try to run it again by `node server.js`

else of that me too i don't know why do you get this error whenever your code is clean, for the future debug upload your clean problem to let the community to debug it .

**Comment by they-cloned-me** [comment]
I will try it as soon as I get off the bus... 🙏
