### ISSUE TITLE
Error: Specified query type "Query" not found in document.

### ISSUE THREAD

**Issue by they-cloned-me** [RomainLanz/adonis-graphql#30]
@RomainLanz, @anaalicefig, @annymosse
For some reason, I still manage to get that error. I have included a screenshot.

![ss](https://user-images.githubusercontent.com/15837064/71459472-47ef3900-276d-11ea-8e3f-911022d8ec5d.png)

_Originally posted by @fsavalam in https://github.com/RomainLanz/adonis-graphql/issues/27#issuecomment-568973153_

**Comment by annymosse** [comment]
**Note:** @fsavalam your `config/graphql.js@options.endpointURL` should be ` '/api/gql'` as you defined in your `routes.js`

**Comment by tuananhzippy** [comment]
For some reason, I still manage to get that error. I have included a screenshot
<img width="1792" alt="Screen Shot 2021-12-24 at 21 37 29" src="https://user-images.githubusercontent.com/13558393/147359677-4864ffba-48e1-4338-929d-dfd970d93adb.png">
.
Please help me. Thank you!
