### ISSUE TITLE
Question: how can I enable autorefresh server when changed *.graphql file?

### ISSUE THREAD

**Issue by yariksav** [RomainLanz/adonis-graphql#6]
How can I enable autorefresh server when changed *.graphql file?
Now after change schema User.graphql nothing happens, I have to restart server or edit any js file
Thank you!

**Comment by RomainLanz** [comment]
Hey @yariksav! 👋 

Currently, you'd need to use `nodemon` directly instead of using the Adonis CLI.
I'll update the CLI to let us add file to watch.

**Comment by RomainLanz** [comment]
It has been added to the CLI.
👉 https://github.com/adonisjs/adonis-cli/blob/develop/src/Commands/Serve/index.js#L34
