### ISSUE TITLE
Wrong file extension when make schema

### ISSUE THREAD

**Issue by yariksav** [RomainLanz/adonis-graphql#7]
When run adonis make:gschema Product it creates app/Schema/Product.js instead app/Schema/Product.graphql

https://github.com/RomainLanz/adonis-graphql/blob/971d19683becdff585f7b85b1324dbbe3f8350c4/commands/MakeSchema.js#L45

**Comment by RomainLanz** [comment]
Hey @yariksav 👋 

Published as `1.0.1-alpha-3`

**Comment by yariksav** [comment]
Thank you, @RomainLanz!
