### ISSUE TITLE
Creating own graphql directive 

### ISSUE THREAD

**Issue by yariksav** [RomainLanz/adonis-graphql#8]
I would want to make own graphql directive for automatically authenticate user in resolvers etc
Something like middleware in adonis

example
```
directive @isAuthenticated on QUERY | FIELD
directive @hasScope (scope: [String]) on QUERY | FIELD

type Query {
  articles: String @isAuthenticated
}

```
For this directives I must create resolver function and put it to specific param **directiveResolvers** in function **makeExecutableSchema**
[docs here](https://www.apollographql.com/docs/graphql-tools/schema-directives.html)

As describes in [this docs](https://www.apollographql.com/docs/graphql-tools/generate-schema.html#makeExecutableSchema) makeExecutableSchema method has params 

```
  typeDefs,
  resolvers, // optional
  logger, // optional
  allowUndefinedInResolve = false, // optional
  resolverValidationOptions = {}, // optional
  directiveResolvers = null, // optional
  schemaDirectives = null,  // optional
  parseOptions = {},  // optional
  inheritResolversFromInterfaces = false  // optio
```
but i's not possible in current implementation 😢 
https://github.com/RomainLanz/adonis-graphql/blob/0604f5ee23fd07de9ed87a1ae8b792405e4efe49/src/Server/index.js#L19

Thank YOU!

**Comment by RomainLanz** [comment]
Hey @yariksav! 👋 

Cool, I'll update the code to make it possible to pass additional params in this function.

**Comment by alanaasmaa** [comment]
Hi, 

I opened a pull request. I hope this helps us to get this feature faster.

**Comment by RomainLanz** [comment]
Closing in favor of the PR.

**Comment by yariksav** [comment]
Hi! How are things going with the 'directives' feature?
